### ISSUE TITLE
Баг с неправильным распознаванием возможных позиций для боя.

### ISSUE THREAD

**Issue by Neketek** [wepp/CheckersServer#2]
Пояснение.
Отсчет координат рисунка начинается стандартно нули в левом нижнем углу, X идет вправо, а Y вверх.
Итак, суть в том, что нашлось кое что, что смутило меня до глубины души.
После того, как бот, который слева(B2), сделал ход, бот, который справа(B1), закономерно ответил ему тем, что походил простой шашкой по всем правилам, которые мы установили.

![screenshot from 2015-12-01 03 11 34](https://cloud.githubusercontent.com/assets/6703760/11489674/1be5d0ac-97da-11e5-9e01-19cc856a61c1.png)

На скрине видно, что о невалидности речи нет, ибо последний сделанный ход подсвечен синим.
Я долго инспектировал свой код, не нашел там ошибок и полез в ваш. Вписав вывод в 

![image](https://cloud.githubusercontent.com/assets/6703760/11489743/bb97fc56-97da-11e5-8426-3259c8fb60ba.png)

я получил следущий ответ.

![image](https://cloud.githubusercontent.com/assets/6703760/11489762/ebed446a-97da-11e5-83b2-ffbe5a23f294.png)

Из этих данных и приложенных к ним рисунков видно, что сервак тупо забил на то, что в том месте, куда вроде бы можно побить, стоит шашка.

Я исправил ошибку, исправьте и вы.

![image](https://cloud.githubusercontent.com/assets/6703760/11489973/e68d277c-97dc-11e5-9b4c-2cd05c799f99.png)

После исправления боты доигрывают партию до ничьи.

**Comment by kemiKondratenko** [comment]
Спасибо!
Исправлю
